/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GDB.gui;

import GDB.dao.DatabaseDAO;
import GDB.pojo.CreateTableObjectPojo;
import GDB.pojo.TableDataStore;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author RISHABH SAHU
 */
public class AddColumnFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddColumnFrame
     */
    int for_edit=0; 
    CreateTableFrame obj=CreateTableObjectPojo.getObj();
    TableNameFrame obj2=null;
    String TableName,ColumnName;
    String DataType,constraint;
    public AddColumnFrame() { 
        initComponents();
        super.setLocationRelativeTo(null);
        btnOK.setEnabled(false);
        jcNull.setSelected(true);
        txtScale.disable();
        lblMsg.setText("Provid  valid column name.");
    }
    public AddColumnFrame(String columnName,String dataType,String size,String scale,String defaultValue)//Fot Edit Button
    {
    this();
    this.ColumnName=columnName;
    txtColumnName.setText(columnName);
    jcDataType.setSelectedItem(dataType);
    txtScale.setText(scale);
    txtSize.setText(size);
    txtDefaultValue.setText(defaultValue);
    this.for_edit=1;
    btnOK.setEnabled(true);
    }
    public AddColumnFrame(TableNameFrame obj,String tableName)//For Add Column in Alter Command
    {
    this();
    this.obj2=obj;
    this.TableName=tableName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcDataType = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        panelConstraint = new javax.swing.JPanel();
        jcPrimary = new javax.swing.JCheckBox();
        jcUnique = new javax.swing.JCheckBox();
        jcNull = new javax.swing.JCheckBox();
        jcIndex = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        txtScale = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDefaultValue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        txtColumnName = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add Column");
        setResizable(false);

        jLabel1.setText("Name:");

        jLabel2.setText("Type:");

        jLabel3.setText("Size:");

        jcDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHAR", "VARCHAR2", "DATE", "NUMBER", "INT", "SMALLINT", "INTEGER", "BLOB", "DECIMAL", "NUMERIC", "REAL", "FLOAT" }));
        jcDataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDataTypeActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        panelConstraint.setBorder(javax.swing.BorderFactory.createTitledBorder("Constraints"));

        jcPrimary.setText("Primary Key");
        jcPrimary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPrimaryActionPerformed(evt);
            }
        });

        jcUnique.setText("Unique");
        jcUnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcUniqueActionPerformed(evt);
            }
        });

        jcNull.setText("Null");
        jcNull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNullActionPerformed(evt);
            }
        });

        jcIndex.setText("Index");

        javax.swing.GroupLayout panelConstraintLayout = new javax.swing.GroupLayout(panelConstraint);
        panelConstraint.setLayout(panelConstraintLayout);
        panelConstraintLayout.setHorizontalGroup(
            panelConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConstraintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcPrimary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcUnique)
                .addGap(10, 10, 10)
                .addComponent(jcNull)
                .addGap(18, 18, 18)
                .addComponent(jcIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelConstraintLayout.setVerticalGroup(
            panelConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConstraintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPrimary, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcUnique)
                    .addComponent(jcNull)
                    .addComponent(jcIndex))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Scale:");

        jLabel5.setText("Default:");

        txtColumnName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColumnNameKeyReleased(evt);
            }
        });

        txtSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSizeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConstraint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcDataType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtColumnName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtScale))
                            .addComponent(txtDefaultValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtColumnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefaultValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(panelConstraint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       this.dispose();
       if(obj2==null)
       {   
       obj.enable();
       obj.setVisible(true);
       }
       else
       obj2.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jcDataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDataTypeActionPerformed
        DataType=jcDataType.getSelectedItem().toString();
        txtSize.enable();
        if(DataType.equals("REAL")||DataType.equals("SMALLINT")||DataType.equals("INTEGER")||DataType.equals("BLOB")||DataType.equals("DATE")||DataType.equals("INT"))
        txtSize.disable();
        else if(DataType.equals("FLOAT")||DataType.equals("DECIMAL")||DataType.equals("NUMERIC")||DataType.equals("NUMBER"))
        txtScale.enable();
        else
        txtScale.disable();
    }//GEN-LAST:event_jcDataTypeActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String ColName= txtColumnName.getText();
        DataType = jcDataType.getSelectedItem().toString();
        String size;
        String scale=txtScale.getText();
        String defaultValue=txtDefaultValue.getText();
        if(txtSize.getText().isEmpty()&&(DataType.equals("VARCHAR2")||DataType.equals("CHAR")||DataType.equals("NUMBER")||DataType.equals("FLOAT")||DataType.equals("DECIMAL")||DataType.equals("NUMRIC")))
          size="1";
        else 
          size=txtSize.getText();
       if(obj2!=null)
       {
        String strQue="";
        if(DataType.equals("REAL")||DataType.equals("SMALLINT")||DataType.equals("INTEGER")||DataType.equals("BLOB")||DataType.equals("DATE")||DataType.equals("INT"))
         strQue="ALTER TABLE "+TableName+" ADD "+ColName+" "+DataType;
        else
         strQue="ALTER TABLE "+TableName+" ADD "+ColName+" "+DataType+"("+size+")";
            try
            {DatabaseDAO.runQuery2(strQue);
             JOptionPane.showMessageDialog(null, "Column Added Successfully.","Success ",JOptionPane.INFORMATION_MESSAGE);}
            catch(SQLException ex){JOptionPane.showMessageDialog(null, "Column is not Added ","Error ",JOptionPane.ERROR_MESSAGE);} 
       }
       if(obj2==null)
       {
       if(for_edit==0){    
       TableDataStore.setColumnName(ColName);
       TableDataStore.setDataType(DataType);
       TableDataStore.setSize(size);
       TableDataStore.setScale(scale);
       TableDataStore.setDefaultValue(defaultValue);   
       //TableDataStore.setkeyConstraint(constraint);
       this.dispose();
       obj.enable();
       obj.setVisible(true);
       obj.showData();
       }else
       {
       this.dispose();
       obj.enable();
       obj.setVisible(true);    
       obj.showEdit(ColName,DataType,size,scale,defaultValue);
       }
       }
    }//GEN-LAST:event_btnOKActionPerformed

    private void jcPrimaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPrimaryActionPerformed
        jcNull.setSelected(false);
        jcUnique.setSelected(true);
        constraint=jcPrimary.getText();
    }//GEN-LAST:event_jcPrimaryActionPerformed

    private void jcNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNullActionPerformed
        jcPrimary.setSelected(false);
        constraint=jcNull.getText();
    }//GEN-LAST:event_jcNullActionPerformed

    private void jcUniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcUniqueActionPerformed
      constraint=jcUnique.getText();
       if(jcPrimary.isSelected())
      {
        jcNull.setSelected(false);
        jcPrimary.setSelected(false);   
      }
      if(jcUnique.isSelected())
      {
      jcIndex.setSelected(true);
      jcIndex.disable();
      }
      else
      {
      jcIndex.setSelected(false);
        jcIndex.enable();
      }
      if(jcIndex.isSelected())
          jcIndex.disable();
    }//GEN-LAST:event_jcUniqueActionPerformed

    private void txtColumnNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnNameKeyReleased
       btnOK.setEnabled(true);
        lblMsg.setText("");
       if(txtColumnName.getText().isEmpty())
        {
        btnOK.setEnabled(false);
        lblMsg.setText("Provid valid column name.");
        }
    }//GEN-LAST:event_txtColumnNameKeyReleased

    private void txtSizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeKeyReleased
    if(txtSize.getText().isEmpty())
    {
    btnOK.setEnabled(true);
    lblMsg.setText("");
    }
    else
    {
      try 
      {
      Integer.parseInt(txtSize.getText());
      btnOK.setEnabled(true);
      lblMsg.setText("");
      } 
    catch (NumberFormatException e) 
     {
      lblMsg.setText("Size must be a valid number");
      btnOK.setEnabled(false);
     }
    }
    }//GEN-LAST:event_txtSizeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddColumnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddColumnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddColumnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddColumnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddColumnFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcDataType;
    private javax.swing.JCheckBox jcIndex;
    private javax.swing.JCheckBox jcNull;
    private javax.swing.JCheckBox jcPrimary;
    private javax.swing.JCheckBox jcUnique;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JPanel panelConstraint;
    private javax.swing.JTextField txtColumnName;
    private javax.swing.JTextField txtDefaultValue;
    private javax.swing.JTextField txtScale;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
